[project]
name = "firstcommit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yosuf20", email = "jyosuf6@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.96",
    "ddgs>=9.16.0",
    "fastapi>=0.141.1",
    "openai>=3.15.0",
    "python-dotenv>=1.2.3",
    "strands-agents>=1.56.0",
    "strands-agents-tools>=0.8.9",
    "uvicorn>=0.53.0",
]

[project.scripts]
firstcommit = "firstcommit:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
